### ISSUE TITLE
Feature request: Specify Square to cut out of a slide

### ISSUE THREAD

**Issue by Clindbergh** [musically-ut/anki-slides-import#3]
Thanks for the addon, nice idea!

It would be nice if one could specify which part of the slide is used to create the images from (instead of using the entire slide). This way common (distracting) headers and footers can be removed from the image. Those could either be added as a commandline argument (such as `--dimensions 100:100:400:400` where each number represents a corner) or added to the notes file (probably makes more sense).

**Comment by musically-ut** [comment]
That is an interesting idea and not too hard to implement (will need changes only here: https://github.com/musically-ut/anki-slides-import/blob/master/slidesimport/pdfpages.py).

Do you mind if I ask you how you use the addon and whether you will be interested in implementing this feature?

**Comment by Clindbergh** [comment]
I see, it's probably not too hard. However I'm quite busy at the moment (learning) and I have never programmed in Python before.

I tried to use it to import slides from lectures, however I failed installing it on windows without further investigating.

**Comment by musically-ut** [comment]
Looks like @barryridge was able to resolve the issue through his excellent PR a while ago. So I'll close the issue for now.
