### ISSUE TITLE
module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by herebcirelapsed** [musically-ut/anki-slides-import#9]
Hi,

I'm happy to see a tool like this in development since I'm doing a tough degree 
[ch513notes__electronic_conduction.txt](https://github.com/musically-ut/anki-slides-import/files/6410860/ch513notes__electronic_conduction.txt)
program in school: I hope it will see more updates sometime. I'm running on Mac OS, and I encountered an error message after the following command, per the docs:
```
slides2anki /Users/Usr/Desktop/ch513notes__electronic_conduction.txt /Users/Usr/Downloads/Electrical+Conductivity-2021-revised.pdf ch513_econductivity_deck -U "/Users/Usr/Library/Application Support/Anki2/User_1"
```

And here was the result/error:

```
Verifying arguments ...
Done.
Reading files ...
Traceback (most recent call last):
  File "/Users/Usr/anaconda3/bin/slides2anki", line 8, in <module>
    sys.exit(run())
  File "/Users/Usr/anaconda3/lib/python3.8/site-packages/slidesimport/slidesimport.py", line 92, in run
    notes = Parser(open(notesFilePath, 'r')).getNotesAndCropsParsing()
  File "/Users/Usr/anaconda3/lib/python3.8/site-packages/slidesimport/parser.py", line 99, in __init__
    slideQList[slideNum].append(cgi.escape(lineMatch.group('line')))
AttributeError: module 'cgi' has no attribute 'escape'
(base) Usr@Usr-MacBook-Pro-2 ~ % 
```

Did I do something wrong? If not, is there any fix at present?

Any guidance would be appreciated: 67 slides is plenty to do by hand, anyhow, haha.

-herebcirelapsed

**Comment by musically-ut** [comment]
Oh, wow. `escape` has not been in `cgi` for a while now (since Python 3.2, IIRC).

Let me replace that with `html.escape` 🤷‍♀️

**Comment by musically-ut** [comment]
@herebcirelapsed Can you give it a try now.

And all the best for your degree!
